---
abstract: 'DateTime factory for web apps'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Web
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0
  DateTime::Format::HTTP: 0
  DateTime::Format::Mail: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::W3CDTF: 0
  DateTime::Locale: 0
  DateTime::TimeZone: 0
  Scalar::Util: 0
  Test::More: 0.47
  Test::UseAllModules: 0.09
version: 0.05
